#!/bin/sh

ino=${1}
inodir=${ino%/*}
pwd=$(cd ${0%/*}; pwd)
valgrind="$(which valgrind)"

if [ ! -r "${ino}" ]; then
	echo "available:"
	i=0
	for ino in ../examples/*/*.ino; do
		i=$((i+1))
		echo "	${i}: ./runino $ino"
	done
	if [ ${i} = 1 ]; then
		ans=1
		echo "running ${ino}"
	else
		echo "choice?"
		read ans
	fi
	i=0
	for ino in ../examples/*/*.ino; do
		i=$((i+1))
		[ ${i} = "$ans" ] && break
	done
	[ -r "$ino" ] || exit 1
fi

inoname=${ino##*/}

posix=${pwd}/arduino2posix
ustr=${pwd}/..
uprintf=${pwd}/../../uprintf
g++ -Wall -Wextra -std=gnu++11 -g -DARDUINO_EMU=1 \
	-DUPRINTF_FLOAT=1 \
	-I${posix} -I${ustr} -I${uprintf} -I${inodir}/../.. \
	-include $posix/Arduino.h \
	-include $ustr/ustr-cpy.cpp \
	-include $ustr/ustr-len.cpp \
	-include $ustr/ustr-cmp.cpp \
	-include $ustr/ustr-chr.cpp \
	$posix/arduino.cpp  \
	-include ${ino} \
	-o ${inoname}.emu \
	-lcurses \
&& ${valgrind} ./${inoname}.emu "$@"
